name: Continuous deployment
on: [pull_request]
jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: cd app && npm install
      - name: Install dependencies
        run: cd app && npm run lint